version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/marcosnav/bloggo
    environment:
      - TEST_RESULTS: /tmp/test-results
      - GOCACHE: "/tmp/go/cache"
      - DEP_VERSION: 0.5.3
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - restore_cache:
          key: gopkg-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
          paths:
            - /go/src/github.com/marcosnav/bloggo/vendor
      - run:
          name: download-libraries
          command: |
            if [ ! -d /go/src/github.com/marcosnav/bloggo/vendor ]; then
              curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o /go/bin/dep
              chmod +x /go/bin/dep
              /go/bin/dep ensure
            fi
      - save_cache:
          key: gopkg-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
          paths:
            - /go/src/github.com/marcosnav/bloggo/vendor
      - restore_cache:
          keys:
            - build-cache-{{ .Branch }}-{{ .Environment.CIRCLE_PREVIOUS_BUILD_NUM }}
          paths:
            - /tmp/go/cache
      - run:
          name: test
          command: |
            mkdir -p $GOCACHE
            gotestsum --junitfile coverage.xml -- -race ./...
            mv coverage.xml $TEST_RESULTS
      - save_cache:
          key: build-cache-{{ .Branch }}-{{ .Environment.CIRCLE_BUILD_NUM }}
          paths:
            - /tmp/go/cache
      - store_artifacts:
          path: /tmp/test-results
      - store_test_results:
          path: /tmp/test-results